micronaut:
  application:
    name: sub-pub
kafka:
  topics:
    requestTopic: request
    responseTopic: response
  bootstrap:
    servers: localhost:9092

commands:
  type:
    CREATE: CreateStrategy
    UPDATE: UpdateStrategy
    DELETE: DeleteStrategy
    READ: ReadStrategy
